branches:
  - name: main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/npm"
    - npmPublish: false
  - - "@semantic-release/exec"
    - publishCmd: yarn npm publish
  - - "@semantic-release/git"
    - assets:
        - package.json
        - yarn.lock
        - CHANGELOG.md
      message: "chore(release): v${nextRelease.version}\n\n${nextRelease.notes} [skip ci]"
