apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: xm-new-customaction
  title: Template with XM Custom action
  description: Create a file via custom action and submit it to GitLab via MR
spec:
  owner: user:guest
  type: gitlab-mr-template

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in the info
      required:
        - gitlabtoken
      properties:
        gitlabtoken:
          title: GitLab Token
          type: string
          description: Gitlab access token used to submit the Merge Request.
          ui:widget: password
          ui:field: GitlabPATSelect
          ui:autofocus: true
        filename:
          title: File name
          type: string
          description: File name
        contents:
          title: Contents
          type: string
          description: File Contents

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: xm-create-file
      name: XM Create File
      action: xm:custom-create-file
      input:
        filename: ${{ parameters.filename }}
        contents: ${{ parameters.contents }}

    - id: debug-printout
      name: debug print
      action: debug:log
      input:
        listWorkspace: true

    - id: creategitlabmr
      name: Create GitLab Merge Request
      action: publish:gitlab:merge-request
      input:
        repoUrl: gitlab.xm.com/bproca/backstagetarget?owner=bproca&repo=backstagetarget
        title: Add Okta config for new app ${{ parameters.filename }}
        description: Generated by Backstage
        branchName: new-file-${{ parameters.filename }}
        targetPath: "."
        token: ${{ parameters.gitlabtoken }}
        commitAction: "create"
        asignee: "bproca"
        removeSourceBranch: true

    - id: debug-printout
      name: debug print
      action: debug:log
      input:
        message: Finished GitLab Merge Request!! RemoteURL is ${{ steps.creategitlabmr.output.mergeRequestUrl }}!
        listWorkspace: true

  output:
    links:
      - title: Go to Gitlab MR
        icon: catalog
        url: ${{ steps.creategitlabmr.output.mergeRequestUrl }}
